<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-54LH6GD" ignored="2" name="Default test" tests="2" failures="0" timestamp="2020-08-17T22:41:26 IST" time="35.706" errors="0">
  <testcase name="@BeforeMethod openApplication" time="35.645" classname="generic.Generic_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at generic.FileManager.getQATUrl(FileManager.java:22)
at generic.Generic_Test.openApplication(Generic_Test.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase name="@AfterMethod closeAppn" time="-1.597684285849E9" classname="generic.Generic_Test">
    <skipped/>
  </testcase> <!-- @AfterMethod closeAppn -->
  <testcase name="@BeforeMethod openApplication" time="-1.597684285851E9" classname="generic.Generic_Test">
    <skipped/>
  </testcase> <!-- @BeforeMethod openApplication -->
  <testcase name="@AfterMethod closeAppn" time="-1.597684285855E9" classname="generic.Generic_Test">
    <skipped/>
  </testcase> <!-- @AfterMethod closeAppn -->
  <testcase name="sendBugReport" time="0.0" classname="regressionScripts.Regression">
    <skipped/>
  </testcase> <!-- sendBugReport -->
  <testcase name="validLoginLogout" time="0.0" classname="regressionScripts.Regression">
    <skipped/>
  </testcase> <!-- validLoginLogout -->
  <testcase name="InvalidLogin" time="0.0" classname="regressionScripts.Regression">
    <ignored/>
  </testcase> <!-- InvalidLogin -->
  <testcase name="verifyActitimeversion" time="0.0" classname="regressionScripts.Regression">
    <ignored/>
  </testcase> <!-- verifyActitimeversion -->
</testsuite> <!-- Default test -->
