<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JHCO5B84" ignored="2" name="Test" tests="2" failures="1" timestamp="2020-08-15T17:25:02 IST" time="34.081" errors="0">
  <testcase name="sendBugReport" time="8.604" classname="regressionScripts.Regression">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at regressionScripts.Regression.sendBugReport(Regression.java:108)
at java.util.ArrayList.forEach(ArrayList.java:1234)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:744)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- sendBugReport -->
  <testcase name="validLoginLogout" time="5.8" classname="regressionScripts.Regression"/>
  <testcase name="InvalidLogin" time="0.0" classname="regressionScripts.Regression">
    <ignored/>
  </testcase> <!-- InvalidLogin -->
  <testcase name="verifyActitimeversion" time="0.0" classname="regressionScripts.Regression">
    <ignored/>
  </testcase> <!-- verifyActitimeversion -->
</testsuite> <!-- Test -->
